spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airdnd?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    access-key: dev-access-secret-key-that-is-long-enough

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}

